#!/usr/bin/env python3
"""
Deuterated PDB Generator with Genetic Algorithm
================================================

Main script to generate a population of deuteration patterns,
create corresponding deuterated PDBs, run SANS simulation,
and evaluate fitness automatically.

Key design principles:
  - Each chromosome carries a ``generation`` and ``index`` attribute that
    reflect when/where it was *first created*.  These attributes are preserved
    when a chromosome is selected (tier-1) and carried over to the next
    generation, so its PDB and SANS files keep their original name forever.
  - File naming: gen{W:02d}_Chr{X:03d}_d2o{Y:03d}_deut{Z:02d}.pdb
      W = chromosome.generation  (creation generation)
      X = chromosome.index       (1-based position in creation population)
      Y = D2O percentage
      Z = number of deuterated amino acid types
  - Per-generation workflow:
      1. Generate PDB files for all NEW chromosomes (tier-2/3 only after gen 0)
      2. Run Pepsi-SANS only on those new PDB files (tier-1 SANS outputs are reused)
      3. Evaluate fitness of ALL .dat files in primus_out by filename matching
      4. Build ``sorted_indices`` (descending fitness) for display/summary/selection
      5. Validate elitism: best fitness must never decrease
      6. Clean up non-tier-1 PDB and SANS files before the next generation

Directory structure created:
    <output_dir>/
        ├── gen00_Chr001_d2o042_deut05.pdb   (stays forever if in tier-1)
        ├── gen01_Chr004_d2o030_deut08.pdb   (tier-2/3 created in gen 1)
        ├── ...
        ├── generation_00_summary.txt
        ├── best_fitness_summary.csv
        └── ref/
            ├── <protein>_total_deuteration.pdb
            └── <protein>_total_protonation.pdb

SANS data (generated by the batch script) stored in:
    <prefix>_primus_out/
        ├── gen00_Chr001_d2o042_deut05.dat   (tier-1: kept across gens)
        ├── gen01_Chr004_d2o030_deut08.dat
        └── ref/
            ├── <protein>_total_deuteration.dat
            └── <protein>_total_protonation.dat

Usage examples:
  # Minimal
  python generate_deuterated_pdbs.py input.pdb

  # Full CLI control
  python generate_deuterated_pdbs.py input.pdb -p 60 -e 5 -g 20 \\
      --d2o-var 10 -m 0.2 -c 0.9 --seed 123 --output_dir results \\
      --q-max 0.35 --ratio-threshold 0.05

  # With config file (CLI overrides INI)
  python generate_deuterated_pdbs.py input.pdb --config ga_config.ini -g 50
"""

import os
import sys
import argparse
import random
import logging
import subprocess
import configparser
import tempfile
import time
from pathlib import Path
from typing import List, Dict, Any, Optional, Set

import numpy as np

from __init__ import (
    AMINO_ACIDS,
    Chromosome,
    PopulationGenerator,
    restrictions as default_restrictions,
)
from pdb_deuteration import PdbDeuteration
from fitness_evaluation import evaluate_population_fitness

# ============================================================================
#                           LOGGING CONFIGURATION
# ============================================================================

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    datefmt='%H:%M:%S'
)
logger = logging.getLogger(__name__)


# ============================================================================
#                           FILENAME HELPERS
# ============================================================================

def get_pdb_filename(chrom: Chromosome) -> str:
    """
    Derive the PDB filename from the chromosome's intrinsic attributes.

    Format: gen{generation:02d}_Chr{index:03d}_d2o{d2o:03d}_deut{n_deut:02d}.pdb

    Because generation and index are frozen at chromosome creation and preserved
    on copy (tier-1), the filename is stable across generations for selected
    individuals.
    """
    num_deut = sum(chrom.deuteration)
    return (f"gen{chrom.generation:02d}_Chr{chrom.index:03d}"
            f"_d2o{chrom.d2o:03d}_deut{num_deut:02d}.pdb")


def get_sorted_indices(population: List[Chromosome]) -> List[int]:
    """
    Return the indices into *population* sorted by descending fitness.

    Usage:
        sorted_indices = get_sorted_indices(population)
        best_chrom = population[sorted_indices[0]]
    """
    return sorted(
        range(len(population)),
        key=lambda i: population[i].fitness if population[i].fitness is not None else 0.0,
        reverse=True
    )


# ============================================================================
#                           ARGUMENT PARSING
# ============================================================================

def parse_arguments():
    """Parse command-line arguments for the genetic algorithm workflow."""
    parser = argparse.ArgumentParser(
        description=(
            "Generate deuterated PDBs using a genetic algorithm "
            "and evaluate fitness via Pepsi-SANS"
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__
    )

    # ---- Positional ----
    parser.add_argument('pdb_file', type=str, help='Source PDB file to deuterate')

    # ---- Config file ----
    parser.add_argument(
        '--config', type=str, metavar='FILE',
        help='Configuration INI file (CLI arguments override INI)'
    )

    # ---- I/O ----
    io = parser.add_argument_group('Input/Output')
    io.add_argument(
        '--output_dir', type=str,
        help='Output directory (default: <pdb_basename>_deuterated_pdbs)'
    )
    io.add_argument(
        '--batch_script', type=str, default='./process_pdb.sh',
        help='Path to the batch processing script (default: ./process_pdb.sh)'
    )

    # ---- Population ----
    pop = parser.add_argument_group('Population parameters')
    pop.add_argument('-p', '--population_size', type=int,
                     help='Population size (MUST be a multiple of 3). Default: 6')
    pop.add_argument('-e', '--elitism', type=int,
                     help='Elite individuals preserved (≤ population_size/3). Default: 2')
    pop.add_argument('--d2o-var', '--d2o_variation_rate', dest='d2o_variation_rate',
                     type=int, help='Max D2O variation amplitude (0-100). Default: 5')
    pop.add_argument('--d2o', type=int, nargs='+', default=None, metavar='VALUE',
                     help=(
                         'Lock D2O to a fixed list of values (e.g. --d2o 0 42 100). '
                         'When set, d2o_variation_rate is ignored and every chromosome '
                         'draws its D2O uniformly from this list.'
                     ))

    # ---- Genetic ----
    gen = parser.add_argument_group('Genetic parameters')
    gen.add_argument('-m', '--mutation_rate', type=float,
                     help='Mutation rate (0.0-1.0). Default: 0.15')
    gen.add_argument('-c', '--crossover_rate', type=float,
                     help='Crossover rate (0.0-1.0). Default: 0.8')

    # ---- Execution ----
    exc = parser.add_argument_group('Execution parameters')
    exc.add_argument('-g', '--generations', type=int,
                     help='Number of generations. Default: 1')
    exc.add_argument('--seed', type=int,
                     help='Random seed for reproducibility. Default: 1')

    # ---- Fitness ----
    fit = parser.add_argument_group('Fitness evaluation parameters')
    fit.add_argument('--q-max', type=float,
                     help='Max q value for truncation (Å⁻¹). Default: 0.3')
    fit.add_argument('--ratio-threshold', type=float,
                     help='Min Imax/background ratio to accept a curve. Default: 0.01')
    fit.add_argument('--i0-threshold', type=float, help=argparse.SUPPRESS)
    fit.add_argument('--deut-ref', type=str,
                     help='Exact filename of deuterated reference inside ref/ (auto-detected if not given)')
    fit.add_argument('--prot-ref', type=str,
                     help='Exact filename of protonated reference inside ref/ (auto-detected if not given)')

    # ---- Verbosity ----
    parser.add_argument('--verbose', action='store_true', help='Enable debug logging')

    args = parser.parse_args()
    if args.verbose:
        logger.setLevel(logging.DEBUG)

    return args


# ============================================================================
#                     CONFIGURATION LOADING & MERGING
# ============================================================================

def load_config_ini(path: str) -> Dict[str, Any]:
    """Load genetic algorithm configuration from an INI file."""
    if not Path(path).exists():
        raise FileNotFoundError(f"Config file not found: {path}")

    config = configparser.ConfigParser()
    config.read(path)
    cfg: Dict[str, Any] = {}

    if config.has_section("POPULATION"):
        cfg["population_size"]   = config.getint("POPULATION", "population_size", fallback=None)
        cfg["elitism"]           = config.getint("POPULATION", "elitism", fallback=None)
        cfg["d2o_variation_rate"]= config.getint("POPULATION", "d2o_variation_rate", fallback=None)

    if config.has_section("GENETIC"):
        cfg["mutation_rate"]  = config.getfloat("GENETIC", "mutation_rate",  fallback=None)
        cfg["crossover_rate"] = config.getfloat("GENETIC", "crossover_rate", fallback=None)

    if config.has_section("EXECUTION"):
        cfg["generations"] = config.getint("EXECUTION", "generations", fallback=None)
        seed_val = config.get("EXECUTION", "seed", fallback=None)
        cfg["seed"] = int(seed_val) if seed_val and seed_val.strip() != "" else None

    if config.has_section("RESTRICTIONS"):
        cfg["restrictions"] = [
            config.getboolean("RESTRICTIONS", aa.code_3, fallback=True)
            for aa in AMINO_ACIDS
        ]

    if config.has_section("FITNESS"):
        cfg["q_max"]           = config.getfloat("FITNESS", "q_max",           fallback=None)
        cfg["ratio_threshold"] = config.getfloat("FITNESS", "ratio_threshold",  fallback=None)
        cfg["deut_ref"]        = config.get("FITNESS", "deut_ref",              fallback=None)
        cfg["prot_ref"]        = config.get("FITNESS", "prot_ref",              fallback=None)

    # [D2O] section — optional fixed D2O list
    raw_d2o = config.get("D2O", "d2o", fallback="None").strip()
    if raw_d2o.lower() == "none":
        cfg["d2o"] = None
    else:
        try:
            cfg["d2o"] = [int(x) for x in raw_d2o.split()]
        except ValueError:
            raise ValueError(f"Invalid D2O list in config file [D2O] d2o = {raw_d2o}")

    return cfg


def merge_config(cli_args: argparse.Namespace,
                 ini_cfg: Optional[Dict] = None) -> Dict[str, Any]:
    """Merge CLI arguments with INI configuration (CLI takes precedence)."""
    ini_cfg = ini_cfg or {}

    def pick(cli_val, ini_val, default):
        return cli_val if cli_val is not None else (ini_val if ini_val is not None else default)

    return {
        # I/O
        "output_dir":        pick(cli_args.output_dir,  ini_cfg.get("output_dir"),  None),
        "batch_script":      pick(cli_args.batch_script, ini_cfg.get("batch_script"), "./process_pdb.sh"),
        # Population
        "population_size":   pick(cli_args.population_size,   ini_cfg.get("population_size"),   6),
        "elitism":           pick(cli_args.elitism,           ini_cfg.get("elitism"),           2),
        "d2o_variation_rate":pick(cli_args.d2o_variation_rate,ini_cfg.get("d2o_variation_rate"),5),
        # Genetic
        "mutation_rate":     pick(cli_args.mutation_rate,     ini_cfg.get("mutation_rate"),     0.15),
        "crossover_rate":    pick(cli_args.crossover_rate,    ini_cfg.get("crossover_rate"),    0.8),
        # Execution
        "generations":       pick(cli_args.generations, ini_cfg.get("generations"), 1),
        "seed":              pick(cli_args.seed,         ini_cfg.get("seed"),         1),
        # Fitness
        "q_max":             pick(cli_args.q_max,            ini_cfg.get("q_max"),            0.3),
        "ratio_threshold":   pick(cli_args.ratio_threshold,  ini_cfg.get("ratio_threshold"),  0.01),
        "deut_ref":          pick(cli_args.deut_ref,         ini_cfg.get("deut_ref"),         None),
        "prot_ref":          pick(cli_args.prot_ref,         ini_cfg.get("prot_ref"),         None),
        # Restrictions
        "restrictions":      ini_cfg.get("restrictions", [True] * len(AMINO_ACIDS)),
        # D2O fixed list (None = free variation)
        "d2o":               pick(getattr(cli_args, 'd2o', None), ini_cfg.get("d2o"), None),
        # Metadata
        "config_file":       cli_args.config,
        "verbose":           cli_args.verbose,
        "pdb_file":          cli_args.pdb_file,
    }


def validate_config(cfg: Dict[str, Any]) -> None:
    """Validate all configuration parameters. Raises ValueError on bad values."""
    if cfg["population_size"] <= 0:
        raise ValueError("population_size must be > 0")
    if cfg["population_size"] % 3 != 0:
        raise ValueError(f"population_size must be a multiple of 3 (got {cfg['population_size']})")
    if cfg["elitism"] < 0:
        raise ValueError("elitism must be >= 0")
    if cfg["elitism"] > cfg["population_size"] // 3:
        raise ValueError(f"elitism must be ≤ population_size/3 (max {cfg['population_size'] // 3})")
    if not (0.0 <= cfg["mutation_rate"] <= 1.0):
        raise ValueError("mutation_rate must be in [0.0, 1.0]")
    if not (0.0 <= cfg["crossover_rate"] <= 1.0):
        raise ValueError("crossover_rate must be in [0.0, 1.0]")
    # d2o_variation_rate is only meaningful when no fixed d2o list is given
    if cfg.get("d2o") is None and not (0 <= cfg["d2o_variation_rate"] <= 100):
        raise ValueError("d2o_variation_rate must be in [0, 100]")
    if cfg["generations"] < 1:
        raise ValueError("generations must be >= 1")
    if len(cfg["restrictions"]) != len(AMINO_ACIDS):
        raise ValueError(
            f"restrictions length ({len(cfg['restrictions'])}) != "
            f"number of amino acids ({len(AMINO_ACIDS)})"
        )
    if cfg["q_max"] <= 0:
        raise ValueError("q_max must be positive")
    if not (0.0 <= cfg["ratio_threshold"] <= 1.0):
        raise ValueError("ratio_threshold must be in [0.0, 1.0]")
    if cfg["seed"] is not None and cfg["seed"] < 0:
        raise ValueError("seed must be non-negative")
    # Validate fixed d2o list if provided
    d2o = cfg.get("d2o")
    if d2o is not None:
        if not isinstance(d2o, list) or len(d2o) == 0:
            raise ValueError("d2o must be a non-empty list of integers")
        for v in d2o:
            if not isinstance(v, int):
                raise ValueError(f"d2o value {v!r} is not an integer")
            if not (0 <= v <= 100):
                raise ValueError(f"d2o value {v} is out of range [0, 100]")


# ============================================================================
#                       OUTPUT DIRECTORY
# ============================================================================

def create_output_directory(output_dir: Optional[str],
                             pdb_file: str):
    """Create output directory and ref/ subdirectory. Returns (output_path, ref_path)."""
    if output_dir is None:
        output_path = Path(Path(pdb_file).stem + "_deuterated_pdbs")
    else:
        output_path = Path(output_dir)

    output_path.mkdir(exist_ok=True, parents=True)
    ref_path = output_path / "ref"
    ref_path.mkdir(exist_ok=True)
    logger.info(f"PDB output directory : {output_path.absolute()}")
    return output_path, ref_path


# ============================================================================
#                       PDB GENERATION
# ============================================================================

def create_reference_pdbs(pdb_file: str,
                           ref_dir: Path,
                           restrictions: List[bool]) -> None:
    """Create fully-deuterated and fully-protonated reference PDB files."""
    logger.info(">>> Creating reference PDBs (fully deuterated / protonated)")
    no_restrictions = [True] * len(AMINO_ACIDS)

    # Fully deuterated
    deut_chrom = Chromosome(AMINO_ACIDS, no_restrictions, fixed_d2o=None)
    deut_chrom.deuteration = [True] * len(AMINO_ACIDS)
    deut_chrom.d2o = 100
    deut_pdb = PdbDeuteration(pdb_file)
    deut_pdb.apply_deuteration(deut_chrom.deuteration, deut_chrom.d2o)
    deut_path = ref_dir / f"{Path(pdb_file).stem}_total_deuteration.pdb"
    deut_pdb.save(str(deut_path))
    logger.info(f"  Deuterated reference : {deut_path.name}")

    # Fully protonated
    prot_chrom = Chromosome(AMINO_ACIDS, no_restrictions, fixed_d2o=None)
    prot_chrom.deuteration = [False] * len(AMINO_ACIDS)
    prot_chrom.d2o = 0
    prot_pdb = PdbDeuteration(pdb_file)
    prot_pdb.apply_deuteration(prot_chrom.deuteration, prot_chrom.d2o)
    prot_path = ref_dir / f"{Path(pdb_file).stem}_total_protonation.pdb"
    prot_pdb.save(str(prot_path))
    logger.info(f"  Protonated reference : {prot_path.name}")

def create_protonated_reference_pdbs(pdb_file: str,
                           ref_dir: Path,
                           restrictions: List[bool]) -> None:
    """Create protonated in D2O fully-protonated (100% H2O) reference PDB files."""
    logger.info(">>> Creating reference PDBs (protonated in D2O / protonated in H2O)")
    no_restrictions = [True] * len(AMINO_ACIDS)

    # Protonated in D2O
    deut_chrom = Chromosome(AMINO_ACIDS, no_restrictions, fixed_d2o=None)
    deut_chrom.deuteration = [False] * len(AMINO_ACIDS)
    deut_chrom.d2o = 100
    deut_pdb = PdbDeuteration(pdb_file)
    deut_pdb.apply_deuteration(deut_chrom.deuteration, deut_chrom.d2o)
    print("For protonated in D2O there are :")
    print(f"{deut_pdb.stats['hydrogen_atoms']} hydrogen atoms")
    print(f"{deut_pdb.stats['deuterium_atoms']} deuterum atoms")
    print(f"The %D is {(deut_pdb.stats['deuterium_atoms']/(deut_pdb.stats['deuterium_atoms']+deut_pdb.stats['hydrogen_atoms']))*100:.2f}")
    deut_path = ref_dir / f"{Path(pdb_file).stem}_total_deuteration.pdb"
    deut_pdb.save(str(deut_path))
    logger.info(f"  Deuterated reference : {deut_path.name}")

    # Fully protonated
    prot_chrom = Chromosome(AMINO_ACIDS, no_restrictions, fixed_d2o=None)
    prot_chrom.deuteration = [False] * len(AMINO_ACIDS)
    prot_chrom.d2o = 0
    prot_pdb = PdbDeuteration(pdb_file)
    prot_pdb.apply_deuteration(prot_chrom.deuteration, prot_chrom.d2o)
    print("For protonated in H2O there are :")
    print(f"{prot_pdb.stats['hydrogen_atoms']} hydrogen atoms")
    print(f"{prot_pdb.stats['deuterium_atoms']} deuterum atoms")
    print(f"The %D is {(prot_pdb.stats['deuterium_atoms'] / (prot_pdb.stats['deuterium_atoms'] + prot_pdb.stats['hydrogen_atoms'])) * 100:.2f}")
    prot_path = ref_dir / f"{Path(pdb_file).stem}_total_protonation.pdb"
    prot_pdb.save(str(prot_path))
    logger.info(f"  Protonated reference : {prot_path.name}")

def generate_pdbs_for_chromosomes(pdb_file: str,
                                   chromosomes: List[Chromosome],
                                   output_dir: Path) -> List[str]:
    """
    Generate a deuterated PDB file for each chromosome in *chromosomes*.

    The filename is derived from the chromosome's own generation/index attributes
    via :func:`get_pdb_filename`, so no external index tracking is needed.

    Args:
        pdb_file:    Source (protonated) PDB file.
        chromosomes: Chromosomes to generate PDBs for.
        output_dir:  Directory in which to write the PDB files.

    Returns:
        List of absolute paths (strings) of the generated PDB files.
    """
    logger.info(f"Generating {len(chromosomes)} deuterated PDB file(s)...")
    generated = []
    for chrom in chromosomes:
        filename = get_pdb_filename(chrom)
        out_path = output_dir / filename
        try:
            deuterator = PdbDeuteration(pdb_file)
            deuterator.apply_deuteration(chrom.deuteration, chrom.d2o)
            chrom.H = deuterator.stats['hydrogen_atoms']
            chrom.D = deuterator.stats['deuterium_atoms']
            print("For protonated in D2O there are :")
            print(f"{deuterator.stats['hydrogen_atoms']} hydrogen atoms")
            print(f"{deuterator.stats['deuterium_atoms']} deuterium atoms")
            print(f"The %D is {(deuterator.stats['deuterium_atoms'] / (deuterator.stats['deuterium_atoms'] + deuterator.stats['hydrogen_atoms'])) * 100:.2f}")
            deuterator.save(str(out_path))
            generated.append(str(out_path))
            logger.debug(f"  Written: {filename}")
        except Exception as exc:
            logger.error(f"  FAILED {filename}: {exc}")
    logger.info(f"  {len(generated)} PDB file(s) written.")
    return generated


# ============================================================================
#                       SANS SIMULATION
# ============================================================================

def run_batch_processing(output_dir: Path,
                          batch_script: str,
                          new_pdb_files: Optional[List[str]] = None) -> str:
    """
    Execute the external batch script for Pepsi-SANS simulation.

    Args:
        output_dir:     Directory containing PDB files (and ref/ subfolder).
        batch_script:   Path to the shell script.
        new_pdb_files:  If given, a list of absolute PDB file paths to process.
                        Only these files will be simulated (tier-2/3 incremental
                        update).  If None, all PDB files in output_dir are
                        processed (generation 0 full run).

    Returns:
        Absolute path (string) to the primus_out directory.
    """
    logger.info("=" * 70)
    logger.info(">>> Running Pepsi-SANS simulation…")
    logger.info("=" * 70)

    tmp_list_file: Optional[str] = None
    try:
        if new_pdb_files:
            # Write the list of new PDB files to a temporary text file.
            # The batch script reads this list and processes only those files.
            fd, tmp_list_file = tempfile.mkstemp(suffix=".txt", prefix="pdb_list_")
            with os.fdopen(fd, 'w') as fh:
                for p in new_pdb_files:
                    fh.write(p + "\n")
            cmd = [batch_script, str(output_dir), tmp_list_file]
            logger.info(f"  Incremental mode: {len(new_pdb_files)} new file(s) to simulate")
        else:
            cmd = [batch_script, str(output_dir)]
            logger.info("  Full mode: all PDB files in output directory")

        result = subprocess.run(cmd, check=True, capture_output=True, text=True)
        logger.debug(result.stdout)

        # Derive primus_out directory (same logic as the batch script)
        folder_name = output_dir.name
        prefix = folder_name.replace("_deuterated_pdbs", "")
        primus_dir = str(output_dir.parent / f"{prefix}_primus_out")
        logger.info(f"  SANS data directory  : {primus_dir}")
        return primus_dir

    except subprocess.CalledProcessError as exc:
        logger.error(f"Batch processing failed (exit code {exc.returncode})")
        logger.error(exc.stderr)
        raise RuntimeError(f"Batch script error: {exc}") from exc
    except FileNotFoundError:
        raise RuntimeError(f"Batch script not found: {batch_script}")
    finally:
        if tmp_list_file and os.path.exists(tmp_list_file):
            os.unlink(tmp_list_file)


# ============================================================================
#                       FITNESS EVALUATION
# ============================================================================

def evaluate_fitness(primus_dir: str,
                     population: List[Chromosome],
                     q_max: float,
                     ratio_threshold: float,
                     deut_ref: Optional[str] = None,
                     prot_ref: Optional[str] = None) -> None:
    """
    Evaluate fitness for all chromosomes by matching .dat filenames.

    The function calls :func:`evaluate_population_fitness` which returns raw
    fitness scores for every .dat file found in *primus_dir* (alphabetical
    order).  Each score is then mapped back to the corresponding chromosome
    via the chromosome's expected filename stem.

    Tier-1 chromosomes already have valid .dat files from a previous run;
    their fitness is re-read from those unchanged files (values are identical).

    Args:
        primus_dir:       Path to the Pepsi-SANS output directory.
        population:       Full current population (tier-1 + tier-2 + tier-3).
        q_max:            q truncation limit.
        ratio_threshold:  Minimum Imax/background ratio threshold.
        deut_ref:         Exact deuterated reference filename (or None for auto-detect).
        prot_ref:         Exact protonated reference filename (or None for auto-detect).
    """
    logger.info("=" * 70)
    logger.info(">>> Evaluating fitness from SANS data…")
    logger.info("=" * 70)

    # Build stem → chromosome lookup (one entry per chromosome)
    chrom_by_stem: Dict[str, Chromosome] = {}
    for chrom in population:
        stem = Path(get_pdb_filename(chrom)).stem
        chrom_by_stem[stem] = chrom

    try:
        fitness_scores, dat_files = evaluate_population_fitness(
            directory=primus_dir,
            deut_ref=deut_ref,
            prot_ref=prot_ref,
            q_max=q_max,
            ratio_threshold=ratio_threshold,
        )
    except Exception as exc:
        logger.error(f"Fitness evaluation failed: {exc}")
        raise RuntimeError(f"Fitness evaluation error: {exc}") from exc

    matched = 0
    unmatched_files = []
    for score, file_path in zip(fitness_scores, dat_files):
        stem = Path(file_path).stem
        if stem in chrom_by_stem:
            chrom_by_stem[stem].fitness = float(score)
            matched += 1
        else:
            unmatched_files.append(Path(file_path).name)

    if unmatched_files:
        logger.warning(
            f"  {len(unmatched_files)} .dat file(s) had no matching chromosome: "
            + ", ".join(unmatched_files[:5])
            + (" …" if len(unmatched_files) > 5 else "")
        )

    chromosomes_without_fitness = [
        chrom for chrom in population
        if chrom.fitness == 0.0 and
        Path(get_pdb_filename(chrom)).stem not in {Path(f).stem for f in dat_files}
    ]
    if chromosomes_without_fitness:
        logger.warning(
            f"  {len(chromosomes_without_fitness)} chromosome(s) have no .dat output "
            f"(fitness kept at 0.0)"
        )

    passed = int(np.sum(fitness_scores > 0))
    logger.info(
        f"  Matched {matched}/{len(population)} chromosome(s). "
        f"Passed ratio check: {passed}/{len(fitness_scores)}"
    )


# ============================================================================
#                       FILE CLEANUP
# ============================================================================

def cleanup_non_tier1_files(output_dir: Path,
                             primus_dir: Optional[str],
                             tier1_population: List[Chromosome]) -> None:
    """
    Remove all PDB and SANS output files that do NOT belong to tier-1 chromosomes.

    Tier-1 chromosomes retain their original filenames (gen{W}_Chr{X}…), so
    their files are simply identified by stem and kept.  Everything else under
    the ``gen*_Chr*`` pattern is deleted.

    The ``ref/`` subfolder is never touched.

    Args:
        output_dir:       Directory that contains PDB files.
        primus_dir:       Directory that contains SANS .dat/.out files (may be None).
        tier1_population: Chromosomes selected for tier-1 of the *new* generation.
    """
    tier1_stems: Set[str] = {print(Path(get_pdb_filename(c)).stem) for c in tier1_population}
    tier1_stems: Set[str] = {Path(get_pdb_filename(c)).stem for c in tier1_population}


    # --- PDB files ---
    removed_pdb = 0
    for pdb in list(output_dir.glob("gen*_Chr*.pdb")):
        if pdb.stem not in tier1_stems:
            try:
                pdb.unlink()
                removed_pdb += 1
                logger.debug(f"  Removed PDB: {pdb.name}")
            except OSError as exc:
                logger.warning(f"  Could not remove {pdb.name}: {exc}")

    # --- SANS output files ---
    removed_sans = 0
    if primus_dir:
        primus_path = Path(primus_dir)
        for ext in ('.dat', '.out'):
            for f in list(primus_path.glob(f"gen*_Chr*{ext}")):
                if f.stem not in tier1_stems:
                    try:
                        f.unlink()
                        removed_sans += 1
                        logger.debug(f"  Removed SANS: {f.name}")
                    except OSError as exc:
                        logger.warning(f"  Could not remove {f.name}: {exc}")

    logger.info(
        f"  Cleanup: removed {removed_pdb} PDB, {removed_sans} SANS file(s). "
        f"Kept {len(tier1_stems)} tier-1 file(s)."
    )


# ============================================================================
#                       DISPLAY & SUMMARY
# ============================================================================

def display_population_summary(population: List[Chromosome],
                                sorted_indices: List[int],
                                generation: int) -> None:
    """Log a short summary of the top-3 chromosomes using their original filenames."""
    top_n = min(10, len(sorted_indices))
    logger.info(f"\n>>> Generation {generation} — top {top_n} chromosome(s):")
    for rank in range(top_n):
        chrom = population[sorted_indices[rank]]
        logger.info(
            f"  {rank + 1:2d}. {get_pdb_filename(chrom)}"
            f"  fitness={chrom.fitness:.6f}"
            f"  H={chrom.H}"
            f"  D={chrom.D}"
            f"  %D={(chrom.D/(chrom.H + chrom.D))*100 :.2f}"
            f"  (created gen{chrom.generation:02d} idx{chrom.index:03d})"
        )


def save_population_summary(population: List[Chromosome],
                             sorted_indices: List[int],
                             output_dir: Path,
                             generation: int) -> None:
    """
    Save a detailed ranked summary of the population to a text file.

    Chromosomes are listed in descending fitness order using their original
    (creation) filenames so that every row can be traced back to a specific
    PDB / SANS file.
    """
    summary_file = output_dir / f"generation_{generation:02d}_summary.txt"
    fitness_values = [population[i].fitness for i in sorted_indices
                      if population[i].fitness is not None]

    with open(summary_file, 'w', encoding='utf-8') as fh:
        fh.write("=" * 90 + "\n")
        fh.write(f"POPULATION SUMMARY — GENERATION {generation}\n")
        fh.write("=" * 90 + "\n\n")
        fh.write(f"Population size : {len(population)}\n")
        if fitness_values:
            fh.write(f"Best fitness    : {max(fitness_values):.6f}\n")
            fh.write(f"Average fitness : {float(np.mean(fitness_values)):.6f}\n")
            fh.write(f"Worst fitness   : {min(fitness_values):.6f}\n")
        fh.write("\n")
        fh.write(
            f"{'Rank':<6} {'PDB filename (creation name)':<55} "
            f"{'D2O%':<6} {'AA':<5} {'Fitness':<14} {'Created':<12}\n"
        )
        fh.write("-" * 90 + "\n")
        for rank, idx in enumerate(sorted_indices, 1):
            chrom = population[idx]
            filename = get_pdb_filename(chrom)
            fit_str = f"{chrom.fitness:.6f}" if chrom.fitness is not None else "N/A"
            fh.write(
                f"{rank:<6} {filename:<55} {chrom.d2o:<6} "
                f"{sum(chrom.deuteration):<5} {fit_str:<14} "
                f"gen{chrom.generation:02d}_idx{chrom.index:03d}\n"
            )
        fh.write("=" * 90 + "\n")

    logger.info(f"  Summary saved : {summary_file.name}")


def save_best_fitness_summary(best_chrom: Chromosome,
                               generation: int,
                               summary_path: Path) -> None:
    """
    Append the best chromosome of the current generation to a CSV file.

    Columns:
        generation, fitness, d2o_percent, n_deuterated_aa,
        deuterated_aa_list, pdb_filename,
        created_generation, created_index
    """
    deut_aas = [AMINO_ACIDS[i].code_3
                for i, d in enumerate(best_chrom.deuteration) if d]
    deut_str = ";".join(deut_aas) if deut_aas else "none"
    filename = get_pdb_filename(best_chrom)

    write_header = not summary_path.exists()
    with open(summary_path, 'a', encoding='utf-8') as fh:
        if write_header:
            fh.write(
                "generation,fitness,d2o_percent,n_deuterated_aa,"
                "deuterated_aa_list,pdb_filename,"
                "created_generation,created_index\n"
            )
        fh.write(
            f"{generation},{best_chrom.fitness:.8f},{best_chrom.d2o},"
            f"{sum(best_chrom.deuteration)},{deut_str},{filename},"
            f"{best_chrom.generation},{best_chrom.index}\n"
        )
    logger.info(
        f"  Best fitness CSV updated: gen={generation}, "
        f"fitness={best_chrom.fitness:.6f}, "
        f"D2O={best_chrom.d2o}%, "
        f"file={filename}"
    )


# ============================================================================
#                       ELITISM GUARD
# ============================================================================

def check_fitness_non_decreasing(population: List[Chromosome],
                                  sorted_indices: List[int],
                                  previous_best: Optional[float],
                                  generation: int) -> float:
    """
    Verify that the best fitness is non-decreasing across generations.

    With elitism > 0, the best individual from the previous generation is
    always preserved in tier-1, so the best fitness must never decrease.
    A warning is logged if this invariant is violated.

    Args:
        population:     Current generation's population.
        sorted_indices: Indices sorted by descending fitness.
        previous_best:  Best fitness of the previous generation (None for gen 0).
        generation:     Current generation number (for log messages).

    Returns:
        The current generation's best fitness value.
    """
    current_best = population[sorted_indices[0]].fitness

    if previous_best is None:
        logger.info(f"  Best fitness (gen {generation}): {current_best:.6f}")
    elif current_best < previous_best - 1e-10:
        logger.warning(
            f"  ELITISM VIOLATION at generation {generation}: "
            f"best fitness decreased from {previous_best:.6f} to {current_best:.6f}. "
            f"Check elitism setting and file management."
        )
    else:
        delta = current_best - previous_best
        logger.info(
            f"  Best fitness (gen {generation}): {current_best:.6f} "
            f"(Δ = {delta:+.6f} vs gen {generation - 1})"
        )

    return current_best


# ============================================================================
#                           MAIN EXECUTION
# ============================================================================

def main():
    cli_args = parse_arguments()

    # ---------- Load & merge configuration ----------
    ini_cfg = None
    if cli_args.config:
        try:
            ini_cfg = load_config_ini(cli_args.config)
            logger.info(f"Loaded configuration from: {cli_args.config}")
        except (FileNotFoundError, ValueError) as exc:
            logger.error(f"Config error: {exc}")
            sys.exit(1)

    try:
        cfg = merge_config(cli_args, ini_cfg)
        validate_config(cfg)
    except ValueError as exc:
        logger.error(f"Configuration validation failed: {exc}")
        sys.exit(1)

    # ---------- Random seed ----------
    if cfg["seed"] is not None:
        random.seed(cfg["seed"])
        np.random.seed(cfg["seed"])
        logger.info(f"Random seed set to: {cfg['seed']}")

    # ---------- Display configuration ----------
    logger.info("=" * 70)
    logger.info("DEUTERATED PDB GENERATION — GENETIC ALGORITHM")
    logger.info("=" * 70)
    logger.info(f"Source PDB           : {cfg['pdb_file']}")
    logger.info(f"Population size      : {cfg['population_size']}")
    logger.info(f"Elitism              : {cfg['elitism']}")
    if cfg.get('d2o') is None:
        logger.info(f"D2O variation rate   : ±{cfg['d2o_variation_rate']}%")
    else:
        logger.info(f"D2O fixed values     : {cfg['d2o']}")
    logger.info(f"Mutation rate        : {cfg['mutation_rate']}")
    logger.info(f"Crossover rate       : {cfg['crossover_rate']}")
    logger.info(f"Generations          : {cfg['generations']}")
    logger.info(f"Q max (fitness)      : {cfg['q_max']} Å⁻¹")
    logger.info(f"Ratio threshold      : {cfg['ratio_threshold']}")
    logger.info(f"Batch script         : {cfg['batch_script']}")
    logger.info(f"Output directory     : {cfg['output_dir'] or '(auto)'}")
    if cfg['config_file']:
        logger.info(f"Config file          : {cfg['config_file']}")
    logger.info("=" * 70)

    # ---------- Validate input files ----------
    pdb_path = Path(cfg['pdb_file'])
    if not pdb_path.exists():
        logger.error(f"PDB file not found: {pdb_path}")
        sys.exit(1)
    if not Path(cfg['batch_script']).exists():
        logger.error(f"Batch script not found: {cfg['batch_script']}")
        sys.exit(1)

    # ---------- Create output directories ----------
    output_dir, ref_dir = create_output_directory(cfg['output_dir'], str(pdb_path))
    best_summary_path = output_dir / "best_fitness_summary.csv"

    # ---------- Create reference PDBs ----------
    #fully deuterated / protonated
    #create_reference_pdbs(str(pdb_path), ref_dir, cfg['restrictions'])

    #protonated in D2O / protonated in H2O
    create_protonated_reference_pdbs(str(pdb_path), ref_dir, cfg['restrictions'])

    # ---------- Initialise population generator ----------
    generator = PopulationGenerator(
        aa_list=AMINO_ACIDS,
        modifiable=cfg['restrictions'],
        population_size=cfg['population_size'],
        elitism=cfg['elitism'],
        d2o_variation_rate=cfg['d2o_variation_rate'],
        d2o=cfg['d2o'],
    )
    tier_size = cfg['population_size'] // 3

    # ======================================================================
    #  GENERATION 0 — full initialisation
    # ======================================================================
    logger.info("\n" + "=" * 70)
    logger.info(">>> GENERATION 0 — creating initial population")
    logger.info("=" * 70)

    # Generate chromosomes with generation=0, index=1..N
    population = generator.generate_initial_population(generation=0)
    logger.info(f"Initial population : {len(population)} unique chromosome(s)")

    # Generate ALL PDB files (full run for generation 0)
    generate_pdbs_for_chromosomes(str(pdb_path), population, output_dir)

    # Run Pepsi-SANS on all files (no file list → full mode)
    primus_dir = run_batch_processing(output_dir, cfg['batch_script'])

    # Evaluate fitness via filename matching
    evaluate_fitness(
        primus_dir, population,
        q_max=cfg['q_max'],
        ratio_threshold=cfg['ratio_threshold'],
        deut_ref=cfg['deut_ref'],
        prot_ref=cfg['prot_ref'],
    )

    # Build sorted index list (no reordering of population list itself)
    sorted_indices = get_sorted_indices(population)

    # Fitness guard baseline
    previous_best_fitness = check_fitness_non_decreasing(
        population, sorted_indices, None, generation=0
    )

    display_population_summary(population, sorted_indices, generation=0)
    save_population_summary(population, sorted_indices, output_dir, generation=0)
    save_best_fitness_summary(
        population[sorted_indices[0]], generation=0, summary_path=best_summary_path
    )

    # ======================================================================
    #  SUBSEQUENT GENERATIONS
    # ======================================================================
    for gen in range(1, cfg['generations']):
        logger.info("\n" + "=" * 70)
        logger.info(f">>> GENERATION {gen} — population evolution")
        logger.info("=" * 70)

        # ------------------------------------------------------------------
        # 1. Build a fitness-sorted view for the generator
        #    (generate_next_generation also sorts internally, but passing a
        #     pre-sorted list makes the tier-1 selection deterministic with
        #     respect to ties)
        # ------------------------------------------------------------------
        #sorted_population = [population[i] for i in sorted_indices]

        # ------------------------------------------------------------------
        # 2. Generate new population
        #    • tier1 (indices 0..tier_size-1): copies with original gen/idx
        #    • tier2 (tier_size..2*tier_size-1): new, gen=gen, idx=tier_size+1..2*tier_size
        #    • tier3 (2*tier_size..3*tier_size-1): new, gen=gen, idx=2*tier_size+1..3*tier_size
        # ------------------------------------------------------------------
        new_population = generator.generate_next_generation(
            #previous_population=sorted_population,
            previous_population=population,
            mutation_rate=cfg['mutation_rate'],
            crossover_rate=cfg['crossover_rate'],
            d2o_variation_rate=cfg['d2o_variation_rate'],
            new_generation=gen,
        )
        logger.info(f"New population : {len(new_population)} chromosome(s)")

        tier1 = new_population[:tier_size]
        tier2_and_3 = new_population[tier_size:]
        # ------------------------------------------------------------------
        # 3. Identify tier-1 files to keep; remove all others
        # ------------------------------------------------------------------
        logger.info(
            f"  Tier-1 ({len(tier1)} chromosome(s)): "
            + ", ".join(get_pdb_filename(c) for c in tier1[:3])
            + (" …" if len(tier1) > 3 else "")
        )
        cleanup_non_tier1_files(output_dir, primus_dir, tier1)

        # ------------------------------------------------------------------
        # 4. Generate PDB files for tier-2/3 only
        # ------------------------------------------------------------------
        new_pdb_files = generate_pdbs_for_chromosomes(
            str(pdb_path), tier2_and_3, output_dir
        )

        # ------------------------------------------------------------------
        # 5. Run Pepsi-SANS only on tier-2/3 (incremental mode)
        # ------------------------------------------------------------------
        primus_dir = run_batch_processing(
            output_dir, cfg['batch_script'], new_pdb_files=new_pdb_files
        )

        # ------------------------------------------------------------------
        # 6. Evaluate fitness for the full new population
        #    (tier-1 .dat files are still in primus_dir; their scores are
        #     re-read from the unchanged files — values are identical)
        # ------------------------------------------------------------------
        evaluate_fitness(
            primus_dir, new_population,
            q_max=cfg['q_max'],
            ratio_threshold=cfg['ratio_threshold'],
            deut_ref=cfg['deut_ref'],
            prot_ref=cfg['prot_ref'],
        )

        # ------------------------------------------------------------------
        # 7. Sort and validate
        # ------------------------------------------------------------------
        sorted_indices = get_sorted_indices(new_population)

        previous_best_fitness = check_fitness_non_decreasing(
            new_population, sorted_indices, previous_best_fitness, generation=gen
        )

        display_population_summary(new_population, sorted_indices, generation=gen)
        save_population_summary(new_population, sorted_indices, output_dir, generation=gen)
        save_best_fitness_summary(
            new_population[sorted_indices[0]], generation=gen, summary_path=best_summary_path
        )

        # Update population reference for the next iteration
        population = new_population

    # ======================================================================
    #  FINAL SUMMARY
    # ======================================================================
    logger.info("\n" + "=" * 70)
    logger.info("GENETIC ALGORITHM COMPLETED SUCCESSFULLY!")
    logger.info("=" * 70)
    logger.info(f"Total generations      : {cfg['generations']}")
    logger.info(f"Results in             : {output_dir.absolute()}")
    logger.info(f"SANS data in           : {primus_dir}")
    logger.info(f"Best fitness summary   : {best_summary_path.absolute()}")

    best = population[sorted_indices[0]]
    logger.info(f"\n>>> Best solution found:")
    logger.info(f"  File           : {get_pdb_filename(best)}")
    logger.info(f"  D2O            : {best.d2o}%")
    logger.info(f"  Deuterated AAs : {sum(best.deuteration)}/20")
    logger.info(f"  H              : {best.H}")
    logger.info(f"  D              : {best.D}")
    logger.info(f"  %D            : {(best.D /( best.H + best.D ))*100:.2f}%")
    logger.info(f"  Fitness        : {best.fitness:.6f}")
    logger.info(
        f"  Created at     : generation {best.generation}, "
        f"index {best.index}"
    )
    logger.info("=" * 70)


if __name__ == "__main__":
    try:
        start = time.perf_counter()
        main()
        elapsed = time.perf_counter() - start
        print(f"\nTotal execution time: {elapsed:.2f} s")
    except KeyboardInterrupt:
        logger.warning("\nInterrupted by user")
        sys.exit(1)
    except Exception as exc:
        logger.exception(f"Fatal error: {exc}")
        sys.exit(1)