#!/usr/bin/env python3
"""
Deuterated PDB Generator with Genetic Algorithm
================================================

Main script to generate a population of deuteration patterns,
create corresponding deuterated PDBs, run SANS simulation,
and evaluate fitness automatically.

Directory structure created:
    <output_dir>/
        ├── gen00_*.pdb            # Deuterated PDB files per generation
        ├── generation_*_summary.txt
        ├── best_fitness_summary.csv  # Best chromosome per generation
        └── ref/                  # Reference PDBs (fully deuterated / protonated)

SANS data is generated by a batch script and stored in:
    <prefix>_primus_out/

Usage examples:
  # Minimal (1 generation, population=6, no config)
  python generate_deuterated_pdbs.py input.pdb

  # Full CLI control
  python generate_deuterated_pdbs.py input.pdb -p 60 -e 5 -g 20 \\
      --d2o-var 10 -m 0.2 -c 0.9 --seed 123 --output_dir results \\
      --q-max 0.35 --ratio-threshold 0.05

  # With config file (CLI overrides INI)
  python generate_deuterated_pdbs.py input.pdb --config ga_config.ini -g 50

  # Specify reference file names inside ref/
  python generate_deuterated_pdbs.py input.pdb \\
      --deut-ref D2O_100pc.dat --prot-ref H2O_0pc.dat
"""

import sys
import argparse
import random
import logging
import subprocess
import configparser
import time
from pathlib import Path
from typing import List, Tuple, Dict, Any, Optional

import numpy as np

from __init__ import (
    AMINO_ACIDS,
    Chromosome,
    PopulationGenerator,
    #AA_INDEX,
    restrictions as default_restrictions
)
from pdb_deuteration import PdbDeuteration
from fitness_evaluation import evaluate_population_fitness

# ============================================================================
#                           LOGGING CONFIGURATION
# ============================================================================

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    datefmt='%H:%M:%S'
)
logger = logging.getLogger(__name__)


# ============================================================================
#                           ARGUMENT PARSING
# ============================================================================

def parse_arguments():
    """
    Parse command-line arguments for the genetic algorithm workflow.
    """
    parser = argparse.ArgumentParser(
        description="Generate deuterated PDBs using a genetic algorithm and evaluate fitness via SANS",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__
    )

    # ==================== POSITIONAL ====================
    parser.add_argument(
        'pdb_file',
        type=str,
        help='Source PDB file to deuterate'
    )

    # ==================== CONFIG FILE ====================
    parser.add_argument(
        '--config',
        type=str,
        metavar='FILE',
        help='Configuration INI file (CLI arguments override INI)'
    )

    # ==================== I/O PARAMETERS ====================
    io_group = parser.add_argument_group('Input/Output')
    io_group.add_argument(
        '--output_dir',
        type=str,
        help='Output directory (default: <pdb_basename>_deuterated_pdbs)'
    )
    io_group.add_argument(
        '--batch_script',
        type=str,
        default='./process_pdb.sh',
        help='Path to the batch processing script (default: ./process_pdb.sh)'
    )

    # ==================== POPULATION PARAMETERS ====================
    pop_group = parser.add_argument_group('Population parameters')
    pop_group.add_argument(
        '-p', '--population_size',
        type=int,
        help='Population size (MUST be a multiple of 3). Default: 6'
    )
    pop_group.add_argument(
        '-e', '--elitism',
        type=int,
        help='Number of elite individuals preserved (≤ population_size/3). Default: 2'
    )
    pop_group.add_argument(
        '--d2o-var', '--d2o_variation_rate',
        dest='d2o_variation_rate',
        type=int,
        help='Maximum D2O variation amplitude (0-100). Default: 5'
    )

    # ==================== GENETIC PARAMETERS ====================
    gen_group = parser.add_argument_group('Genetic parameters')
    gen_group.add_argument(
        '-m', '--mutation_rate',
        type=float,
        help='Mutation rate (0.0-1.0). Default: 0.15'
    )
    gen_group.add_argument(
        '-c', '--crossover_rate',
        type=float,
        help='Crossover rate (0.0-1.0). Default: 0.8'
    )

    # ==================== EXECUTION PARAMETERS ====================
    exec_group = parser.add_argument_group('Execution parameters')
    exec_group.add_argument(
        '-g', '--generations',
        type=int,
        help='Number of generations to run. Default: 1'
    )
    exec_group.add_argument(
        '--seed',
        type=int,
        help='Random seed for reproducibility. Default: 1 (set to None for random)'
    )

    # ==================== FITNESS EVALUATION PARAMETERS ====================
    fitness_group = parser.add_argument_group('Fitness evaluation parameters')
    fitness_group.add_argument(
        '--q-max',
        type=float,
        help='Maximum q value for truncation (Å⁻¹). Default: 0.3'
    )
    fitness_group.add_argument(
        '--ratio-threshold',
        type=float,
        help='Minimum Imax/background ratio to accept a curve. Default: 0.01'
    )
    # Kept for backward compatibility with older config files, but no longer used
    fitness_group.add_argument(
        '--i0-threshold',
        type=float,
        help=argparse.SUPPRESS
    )
    fitness_group.add_argument(
        '--deut-ref',
        type=str,
        help='Exact filename of deuterated reference inside ref/ (auto-detected if not given)'
    )
    fitness_group.add_argument(
        '--prot-ref',
        type=str,
        help='Exact filename of protonated reference inside ref/ (auto-detected if not given)'
    )

    # ==================== VERBOSITY ====================
    parser.add_argument(
        '--verbose',
        action='store_true',
        help='Enable debug logging'
    )

    args = parser.parse_args()

    # Set logging level
    if args.verbose:
        logger.setLevel(logging.DEBUG)

    return args


# ============================================================================
#                     CONFIGURATION LOADING & MERGING
# ============================================================================

def load_config_ini(path: str) -> Dict[str, Any]:
    """
    Load genetic algorithm configuration from an INI file.

    Expected sections:
        [POPULATION]
        population_size = int
        elitism = int
        d2o_variation_rate = int

        [GENETIC]
        mutation_rate = float
        crossover_rate = float

        [EXECUTION]
        generations = int
        seed = int (optional)

        [RESTRICTIONS]
        ALA = true/false
        ...

        [FITNESS]   (optional)
        q_max = float
        ratio_threshold = float
        deut_ref = str
        prot_ref = str
    """
    if not Path(path).exists():
        raise FileNotFoundError(f"Config file not found: {path}")

    config = configparser.ConfigParser()
    config.read(path)
    cfg = {}

    # ----- POPULATION -----
    if config.has_section("POPULATION"):
        cfg["population_size"] = config.getint("POPULATION", "population_size", fallback=None)
        cfg["elitism"] = config.getint("POPULATION", "elitism", fallback=None)
        cfg["d2o_variation_rate"] = config.getint("POPULATION", "d2o_variation_rate", fallback=None)

    # ----- GENETIC -----
    if config.has_section("GENETIC"):
        cfg["mutation_rate"] = config.getfloat("GENETIC", "mutation_rate", fallback=None)
        cfg["crossover_rate"] = config.getfloat("GENETIC", "crossover_rate", fallback=None)

    # ----- EXECUTION -----
    if config.has_section("EXECUTION"):
        cfg["generations"] = config.getint("EXECUTION", "generations", fallback=None)
        # seed can be empty -> None
        seed_val = config.get("EXECUTION", "seed", fallback=None)
        cfg["seed"] = int(seed_val) if seed_val and seed_val.strip() != "" else None

    # ----- RESTRICTIONS -----
    if config.has_section("RESTRICTIONS"):
        restrictions = []
        for aa in AMINO_ACIDS:
            # default to True if not specified (backward compatibility)
            val = config.getboolean("RESTRICTIONS", aa.code_3, fallback=True)
            restrictions.append(val)
        cfg["restrictions"] = restrictions

    # ----- FITNESS -----
    if config.has_section("FITNESS"):
        cfg["q_max"] = config.getfloat("FITNESS", "q_max", fallback=None)
        cfg["ratio_threshold"] = config.getfloat("FITNESS", "ratio_threshold", fallback=None)
        # i0_threshold kept for backward compatibility (ignored)
        cfg["deut_ref"] = config.get("FITNESS", "deut_ref", fallback=None)
        cfg["prot_ref"] = config.get("FITNESS", "prot_ref", fallback=None)

    return cfg


def merge_config(cli_args: argparse.Namespace, ini_cfg: Optional[Dict] = None) -> Dict[str, Any]:
    """
    Merge CLI arguments with INI configuration (CLI takes precedence).
    """
    ini_cfg = ini_cfg or {}

    def pick(cli_val, ini_val, default):
        return cli_val if cli_val is not None else (ini_val if ini_val is not None else default)

    # Default values
    defaults = {
        "population_size": 6,
        "elitism": 2,
        "d2o_variation_rate": 5,
        "mutation_rate": 0.15,
        "crossover_rate": 0.8,
        "generations": 1,
        "seed": 1,
        "q_max": 0.3,
        "ratio_threshold": 0.01,
        "deut_ref": None,
        "prot_ref": None,
        "restrictions": [True] * len(AMINO_ACIDS),  # default: all modifiable
        "output_dir": None,
        "batch_script": "./process_pdb.sh",
        "verbose": False,
        "config": None,
    }

    merged = {
        # I/O
        "output_dir": pick(cli_args.output_dir, ini_cfg.get("output_dir"), defaults["output_dir"]),
        "batch_script": pick(cli_args.batch_script, ini_cfg.get("batch_script"), defaults["batch_script"]),

        # Population
        "population_size": pick(cli_args.population_size, ini_cfg.get("population_size"), defaults["population_size"]),
        "elitism": pick(cli_args.elitism, ini_cfg.get("elitism"), defaults["elitism"]),
        "d2o_variation_rate": pick(cli_args.d2o_variation_rate, ini_cfg.get("d2o_variation_rate"), defaults["d2o_variation_rate"]),

        # Genetic
        "mutation_rate": pick(cli_args.mutation_rate, ini_cfg.get("mutation_rate"), defaults["mutation_rate"]),
        "crossover_rate": pick(cli_args.crossover_rate, ini_cfg.get("crossover_rate"), defaults["crossover_rate"]),

        # Execution
        "generations": pick(cli_args.generations, ini_cfg.get("generations"), defaults["generations"]),
        "seed": pick(cli_args.seed, ini_cfg.get("seed"), defaults["seed"]),

        # Fitness
        "q_max": pick(cli_args.q_max, ini_cfg.get("q_max"), defaults["q_max"]),
        "ratio_threshold": pick(cli_args.ratio_threshold, ini_cfg.get("ratio_threshold"), defaults["ratio_threshold"]),
        "deut_ref": pick(cli_args.deut_ref, ini_cfg.get("deut_ref"), defaults["deut_ref"]),
        "prot_ref": pick(cli_args.prot_ref, ini_cfg.get("prot_ref"), defaults["prot_ref"]),

        # Restrictions
        "restrictions": ini_cfg.get("restrictions", defaults["restrictions"]),

        # Metadata
        "config_file": cli_args.config,
        "verbose": cli_args.verbose,
        "pdb_file": cli_args.pdb_file,
    }

    return merged


def validate_config(cfg: Dict[str, Any]) -> None:
    """
    Validate all configuration parameters.
    Raises ValueError if any parameter is invalid.
    """
    # Population
    if cfg["population_size"] <= 0:
        raise ValueError("population_size must be > 0")
    if cfg["population_size"] % 3 != 0:
        raise ValueError(f"population_size must be a multiple of 3 (got {cfg['population_size']})")
    if cfg["elitism"] < 0:
        raise ValueError("elitism must be >= 0")
    if cfg["elitism"] > cfg["population_size"] // 3:
        raise ValueError(f"elitism must be ≤ population_size/3 (max {cfg['population_size'] // 3})")

    # Rates
    if not (0.0 <= cfg["mutation_rate"] <= 1.0):
        raise ValueError("mutation_rate must be in [0.0, 1.0]")
    if not (0.0 <= cfg["crossover_rate"] <= 1.0):
        raise ValueError("crossover_rate must be in [0.0, 1.0]")
    if not (0 <= cfg["d2o_variation_rate"] <= 100):
        raise ValueError("d2o_variation_rate must be in [0, 100]")

    # Execution
    if cfg["generations"] < 1:
        raise ValueError("generations must be >= 1")

    # Restrictions
    if len(cfg["restrictions"]) != len(AMINO_ACIDS):
        raise ValueError(
            f"restrictions length ({len(cfg['restrictions'])}) != "
            f"number of amino acids ({len(AMINO_ACIDS)})"
        )

    # Fitness
    if cfg["q_max"] <= 0:
        raise ValueError("q_max must be positive")
    if not (0.0 <= cfg["ratio_threshold"] <= 1.0):
        raise ValueError("ratio_threshold must be in [0.0, 1.0]")

    # Files (existence checked later)
    if cfg["seed"] is not None and cfg["seed"] < 0:
        raise ValueError("seed must be non-negative")


# ============================================================================
#                     CORE WORKFLOW FUNCTIONS
# ============================================================================

def create_output_directory(output_dir: Optional[str], pdb_file: str) -> Tuple[Path, Path]:
    """Create output directory and ref subdirectory."""
    if output_dir is None:
        output_path = Path(pdb_file).stem + "_deuterated_pdbs"
        output_path = Path(output_path)
    else:
        output_path = Path(output_dir)

    output_path.mkdir(exist_ok=True, parents=True)
    ref_path = output_path / "ref"
    ref_path.mkdir(exist_ok=True)
    logger.info(f"PDB Output directory: {output_path.absolute()}")
    return output_path, ref_path


def generate_pdb_filename(chromosome: Chromosome, index: int, generation: int = 0) -> str:
    """Generate a descriptive PDB filename."""
    num_deut = sum(chromosome.deuteration)
    return f"gen{generation:02d}_chr{index:03d}_d2o{chromosome.d2o:02d}_deutAA{num_deut:02d}.pdb"


def save_population_summary(population: List[Chromosome],
                            output_dir: Path,
                            generation: int = 0) -> None:
    """Save a detailed summary of the population to a text file."""
    summary_file = output_dir / f"generation_{generation:02d}_summary.txt"
    with open(summary_file, 'w', encoding='utf-8') as f:
        f.write("=" * 80 + "\n")
        f.write(f"POPULATION SUMMARY - GENERATION {generation}\n")
        f.write("=" * 80 + "\n\n")
        f.write(f"Population size: {len(population)}\n")

        fitness_values = [c.fitness for c in population if c.fitness is not None]
        if fitness_values:
            f.write(f"Average fitness: {np.mean(fitness_values):.6f}\n")
            f.write(f"Best fitness   : {np.max(fitness_values):.6f}\n")
            f.write(f"Worst fitness  : {np.min(fitness_values):.6f}\n")

        f.write("\n" + "-" * 80 + "\n")
        f.write(f"{'#':<5} {'PDB Filename':<45} {'D2O%':<8} {'AA deut.':<12} {'Fitness':<10}\n")
        f.write("-" * 80 + "\n")
        for i, chrom in enumerate(population, 1):
            filename = generate_pdb_filename(chrom, i, generation) #les nom des fichier sont erronnees
            num_deut = sum(chrom.deuteration)
            fit_str = f"{chrom.fitness:.6f}" if chrom.fitness is not None else "N/A"
            f.write(f"{i:<5} {filename:<45} {chrom.d2o:<8} {num_deut:<12} {fit_str:<10}\n")
        f.write("-" * 80 + "\n\n")
        f.write("=" * 80 + "\n")
    logger.info(f"Summary saved: {summary_file}")


def save_best_fitness_summary(best_chrom: Chromosome,
                              generation: int,
                              summary_path: Path) -> None:
    """
    Append the best chromosome record for this generation to the best fitness summary CSV.

    The CSV contains one row per generation with columns:
        - generation       : generation index
        - fitness          : best raw fitness (area difference)
        - d2o_percent      : D2O percentage of the best chromosome
        - n_deuterated_aa  : number of deuterated amino acid types
        - deuterated_aa_list: semicolon-separated 3-letter codes of deuterated AAs

    Args:
        best_chrom (Chromosome): Best chromosome of this generation
        generation (int): Generation index
        summary_path (Path): Path to the CSV file (created if it does not exist)
    """
    deut_aas = [
        AMINO_ACIDS[i].code_3
        for i, deuterated in enumerate(best_chrom.deuteration)
        if deuterated
    ]
    deut_aa_str = ";".join(deut_aas) if deut_aas else "none"

    write_header = not summary_path.exists()
    with open(summary_path, 'a', encoding='utf-8') as f:
        if write_header:
            f.write("generation,fitness,d2o_percent,n_deuterated_aa,deuterated_aa_list\n")
        f.write(
            f"{generation},{best_chrom.fitness:.8f},"
            f"{best_chrom.d2o},{sum(best_chrom.deuteration)},{deut_aa_str}\n"
        )
    logger.info(
        f"Best fitness summary updated: {summary_path.name} "
        f"(gen {generation}: fitness={best_chrom.fitness:.6f}, "
        f"D2O={best_chrom.d2o}%, AAs=[{deut_aa_str}])"
    )


def run_batch_processing(output_dir: Path, batch_script: str) -> str:
    """Execute the external batch script for SANS simulation."""
    logger.info("=" * 80)
    logger.info(">>> Running batch processing (Pepsi-SANS simulation)...")
    logger.info("=" * 80)
    try:
        result = subprocess.run(
            [batch_script, str(output_dir)],
            check=True,
            capture_output=True,
            text=True
        )
        logger.debug(result.stdout)
        # Infer primus output directory (same logic as the batch script)
        folder_name = output_dir.name
        prefix = folder_name.replace("_deuterated_pdbs", "")
        primus_dir = output_dir.parent / f"{prefix}_primus_out"
        logger.info(f"SANS data generated in: {primus_dir}")
        return str(primus_dir)
    except subprocess.CalledProcessError as e:
        logger.error(f"Batch processing failed (code {e.returncode})")
        logger.error(e.stderr)
        raise RuntimeError(f"Batch script error: {e}")
    except FileNotFoundError:
        raise RuntimeError(f"Batch script not found: {batch_script}")


def evaluate_fitness(primus_output_dir: str,
                     population: List[Chromosome],
                     q_max: float,
                     ratio_threshold: float,
                     deut_ref: Optional[str] = None,
                     prot_ref: Optional[str] = None) -> None:
    """
    Evaluate fitness of all chromosomes using SANS data.

    The dat files returned by evaluate_population_fitness are sorted alphabetically,
    which matches the chromosome order in population (population[i] was written as
    chr{i+1}, so alphabetical order of filenames == population order).
    """
    logger.info("=" * 80)
    logger.info(">>> Evaluating population fitness from SANS data...")
    logger.info("=" * 80)
    try:
        fitness_scores, dat_files = evaluate_population_fitness(
            directory=primus_output_dir,
            deut_ref=deut_ref,
            prot_ref=prot_ref,
            q_max=q_max,
            ratio_threshold=ratio_threshold
        )
        # Assign scores to chromosomes
        min_len = min(len(fitness_scores), len(population))
        for i in range(min_len):
            population[i].fitness = float(fitness_scores[i])
            #test avec bonne fitness tout le temp
            #population[i].fitness = 1.0
        logger.info(f"Fitness evaluation complete. "
                    f"Passed ratio check: {np.sum(fitness_scores > 0)}/{len(fitness_scores)}")
    except Exception as e:
        logger.error(f"Fitness evaluation failed: {e}")
        raise RuntimeError(f"Fitness evaluation error: {e}")


def rename_tier1_files(tier1: List[Chromosome],
                       prev_population_ordered: List[Chromosome],
                       output_dir: Path,
                       primus_dir: Optional[str],
                       prev_gen: int,
                       new_gen: int) -> None:
    """
    Rename PDB (and SANS output) files for tier1 chromosomes from prev_gen to new_gen.

    IMPORTANT: The lookup is done against prev_population_ordered, which is the population
    in the EXACT order it was passed to generate_deuterated_pdbs() in the previous generation.
    This order directly corresponds to the chr index used in filenames:
        prev_population_ordered[0]  → gen{prev_gen}_chr001_...
        prev_population_ordered[1]  → gen{prev_gen}_chr002_...
        ...
    Using sorted_pop instead would give WRONG indices because sorting changes the order.

    For each chromosome in tier1:
    - Find its position in prev_population_ordered (= old file index)
    - Rename gen{prev_gen}_chr{old_idx}_* to gen{new_gen}_chr{new_idx}_*
    - Also rename the corresponding SANS output files (.dat / .out)

    Duplicate chromosomes in tier1 (allowed by probabilistic selection) are skipped
    after the first occurrence; they will have their PDB regenerated.

    Args:
        tier1 (List[Chromosome]): Tier1 chromosomes of the new generation
        prev_population_ordered (List[Chromosome]): Previous generation population in the
            ORIGINAL order used when PDB files were generated (NOT the sorted order)
        output_dir (Path): Directory containing PDB files
        primus_dir (str or None): Directory containing SANS output (.dat/.out) files
        prev_gen (int): Previous generation index
        new_gen (int): New generation index
    """
    # Track which chromosomes have already been renamed (to handle duplicates in tier1)
    already_renamed: set = set()

    for new_idx, chrom in enumerate(tier1, 1):
        chrom_key = (tuple(chrom.deuteration), chrom.d2o)

        # Skip duplicates: they will be regenerated from scratch
        if chrom_key in already_renamed:
            logger.debug(
                f"Tier1 chr{new_idx:03d}: duplicate chromosome in tier1, will be regenerated"
            )
            continue

        # Find the chromosome in the ORDERED previous population.
        # The 1-based position here directly maps to the chr index in filenames.
        old_idx = None
        for j, prev_chrom in enumerate(prev_population_ordered):
            if prev_chrom.deuteration == chrom.deuteration and prev_chrom.d2o == chrom.d2o:
                old_idx = j + 1  # 1-based index == chr number in filename
                break

        if old_idx is None:
            logger.warning(
                f"Tier1 chr{new_idx:03d}: chromosome not found in previous generation's "
                f"ordered population; PDB will be regenerated"
            )
            continue

        num_deut = sum(chrom.deuteration)
        old_stem = (
            f"gen{prev_gen:02d}_chr{old_idx:03d}"
            f"_d2o{chrom.d2o:02d}_deutAA{num_deut:02d}"
        )
        new_stem = (
            f"gen{new_gen:02d}_chr{new_idx:03d}"
            f"_d2o{chrom.d2o:02d}_deutAA{num_deut:02d}"
        )

        # Rename PDB file
        old_pdb = output_dir / f"{old_stem}.pdb"
        new_pdb = output_dir / f"{new_stem}.pdb"
        if old_pdb.exists():
            old_pdb.rename(new_pdb)
            logger.debug(f"Renamed PDB: {old_stem}.pdb -> {new_stem}.pdb")
        else:
            logger.warning(f"PDB not found for renaming: {old_pdb.name}")

        # Rename SANS output files if primus_dir is available
        if primus_dir:
            primus_path = Path(primus_dir)
            for ext in ['.dat', '.out']:
                old_sans = primus_path / f"{old_stem}{ext}"
                new_sans = primus_path / f"{new_stem}{ext}"
                if old_sans.exists():
                    old_sans.rename(new_sans)
                    logger.debug(f"Renamed SANS: {old_sans.name} -> {new_sans.name}")

        already_renamed.add(chrom_key)

    renamed_count = len(already_renamed)
    logger.info(
        f"Tier1 file renaming: {renamed_count} unique chromosome(s) renamed "
        f"from gen{prev_gen:02d} to gen{new_gen:02d}"
    )


def cleanup_non_tier1_files(output_dir: Path,
                             primus_dir: Optional[str],
                             generation: int) -> None:
    """
    Remove all remaining PDB and SANS output files from a given generation.

    This function is called after tier1 files have already been renamed to the new
    generation, so only the non-tier1 files remain under the old generation prefix.

    Args:
        output_dir (Path): Directory containing PDB files
        primus_dir (str or None): Directory containing SANS output files
        generation (int): Generation index whose leftover files should be removed
    """
    pattern = f"gen{generation:02d}_*.pdb"
    removed_pdb = 0
    for pdb in output_dir.glob(pattern):
        try:
            pdb.unlink()
            removed_pdb += 1
        except Exception as e:
            logger.warning(f"Could not remove {pdb.name}: {e}")
    logger.info(f"Removed {removed_pdb} non-tier1 PDB files from generation {generation}")

    if primus_dir:
        primus_path = Path(primus_dir)
        removed_sans = 0
        for ext in ['.dat', '.out']:
            for f in primus_path.glob(f"gen{generation:02d}_*{ext}"):
                try:
                    f.unlink()
                    removed_sans += 1
                except Exception as e:
                    logger.warning(f"Could not remove {f.name}: {e}")
        if removed_sans:
            logger.info(
                f"Removed {removed_sans} non-tier1 SANS output files from generation {generation}"
            )


def generate_deuterated_pdbs(pdb_file: str,
                             population: List[Chromosome],
                             output_dir: Path,
                             generation: int = 0,
                             start_index: int = 1) -> None:
    """
    Generate deuterated PDB files for chromosomes in the population.

    The chromosome at position i in population receives the filename index
    start_index + i, i.e.:
        population[0] → gen{generation}_chr{start_index:03d}_...
        population[1] → gen{generation}_chr{start_index+1:03d}_...
        ...

    This mapping must be preserved so that rename_tier1_files can correctly
    look up file indices from the ordered population list.

    Args:
        pdb_file (str): Source PDB file
        population (List[Chromosome]): Chromosomes to generate PDBs for
        output_dir (Path): Output directory
        generation (int): Generation index (used in filename)
        start_index (int): Starting chromosome index for filename numbering (default: 1)
    """
    logger.info(f"Generating {len(population)} deuterated PDB files (gen {generation})...")
    for i, chrom in enumerate(population, start_index):
        try:
            deuterator = PdbDeuteration(pdb_file)
            deuterator.apply_deuteration(chrom.deuteration, chrom.d2o)
            filename = generate_pdb_filename(chrom, i, generation)
            out_path = output_dir / filename
            deuterator.save(str(out_path))
            logger.debug(f"  [{i:03d}] {filename}")
        except Exception as e:
            logger.error(f"  [{i:03d}] FAILED: {e}")
    logger.info(f"Generation {generation} PDBs created.")


def create_reference_pdbs(pdb_file: str,
                          ref_dir: Path,
                          restrictions: List[bool]) -> None:
    """
    Create fully deuterated and fully protonated reference PDBs.
    restriction are not consider for this reference files
    """
    logger.info(">>> Creating reference PDBs (fully deuterated / protonated)")
    no_restrictions = [True] * len(AMINO_ACIDS)
    # Fully deuterate
    deut_chrom = Chromosome(AMINO_ACIDS, no_restrictions)
    deut_chrom.deuteration = [True] * len(AMINO_ACIDS)
    deut_chrom.d2o = 100
    deut_pdb = PdbDeuteration(pdb_file)
    deut_pdb.apply_deuteration(deut_chrom.deuteration, deut_chrom.d2o)
    # Fix: use f-string with Path / operator
    deut_filename = f"{Path(pdb_file).stem}_total_deuteration.pdb"
    deut_path = ref_dir / deut_filename
    deut_pdb.save(str(deut_path))
    logger.info(f"  Deuterated reference: {deut_path.name}")

    # Fully protonated
    prot_chrom = Chromosome(AMINO_ACIDS, no_restrictions)
    prot_chrom.deuteration = [False] * len(AMINO_ACIDS)
    prot_chrom.d2o = 0
    prot_pdb = PdbDeuteration(pdb_file)
    prot_pdb.apply_deuteration(prot_chrom.deuteration, prot_chrom.d2o)
    prot_filename = f"{Path(pdb_file).stem}_total_protonation.pdb"
    prot_path = ref_dir / prot_filename
    prot_pdb.save(str(prot_path))
    logger.info(f"  Protonated reference: {prot_path.name}")


def display_population_summary(population: List[Chromosome], generation: int) -> None:
    """Print top chromosomes and basic statistics."""
    sorted_pop = sorted(population, key=lambda x: x.fitness if x.fitness else 0, reverse=True)
    logger.info(f"\n>>> Generation {generation} - Top 3 chromosomes:")
    for i in range(min(3, len(sorted_pop))):
        c = sorted_pop[i]
        fit_str = f"{c.fitness:.4f}" if c.fitness else "N/A"
        logger.info(f"  {i + 1}. D2O={c.d2o:2d}%, AA deut={sum(c.deuteration):2d}/20, Fitness={fit_str}")


# ============================================================================
#                           MAIN EXECUTION
# ============================================================================

def main():
    cli_args = parse_arguments()

    # Load config file if provided
    ini_cfg = None
    if cli_args.config:
        try:
            ini_cfg = load_config_ini(cli_args.config)
            logger.info(f"Loaded configuration from: {cli_args.config}")
        except (FileNotFoundError, ValueError) as e:
            logger.error(f"Config error: {e}")
            sys.exit(1)

    # Merge CLI and INI
    try:
        cfg = merge_config(cli_args, ini_cfg)
        validate_config(cfg)
    except ValueError as e:
        logger.error(f"Configuration validation failed: {e}")
        sys.exit(1)

    # Set random seed
    if cfg["seed"] is not None:
        random.seed(cfg["seed"])
        np.random.seed(cfg["seed"])
        logger.info(f"Random seed set to: {cfg['seed']}")

    # Display configuration
    logger.info("=" * 80)
    logger.info("DEUTERATED PDB GENERATION WITH GENETIC ALGORITHM")
    logger.info("=" * 80)
    logger.info(f"Source PDB           : {cfg['pdb_file']}")
    logger.info(f"Population size      : {cfg['population_size']}")
    logger.info(f"Elitism              : {cfg['elitism']}")
    logger.info(f"D2O variation rate   : ±{cfg['d2o_variation_rate']}%")
    logger.info(f"Mutation rate        : {cfg['mutation_rate']}")
    logger.info(f"Crossover rate       : {cfg['crossover_rate']}")
    logger.info(f"Generations          : {cfg['generations']}")
    logger.info(f"Q max (fitness)      : {cfg['q_max']} Å⁻¹")
    logger.info(f"Ratio threshold      : {cfg['ratio_threshold']}")
    logger.info(f"Batch script         : {cfg['batch_script']}")
    logger.info(f"Output directory     : {cfg['output_dir'] or '(auto)'}")
    if cfg['config_file']:
        logger.info(f"Config file          : {cfg['config_file']}")
    logger.info("=" * 80)

    # Check PDB file existence
    pdb_path = Path(cfg['pdb_file'])
    if not pdb_path.exists():
        logger.error(f"PDB file not found: {pdb_path}")
        sys.exit(1)

    # Check batch script
    if not Path(cfg['batch_script']).exists():
        logger.error(f"Batch script not found: {cfg['batch_script']}")
        sys.exit(1)

    # Create output directories
    output_dir, ref_dir = create_output_directory(cfg['output_dir'], str(pdb_path))

    # Path for the best fitness summary CSV (one row appended per generation)
    best_summary_path = output_dir / "best_fitness_summary.csv"

    # Create reference PDBs using the loaded restrictions
    create_reference_pdbs(str(pdb_path), ref_dir, cfg['restrictions'])

    # Initialize population generator
    generator = PopulationGenerator(
        aa_list=AMINO_ACIDS,
        modifiable=cfg['restrictions'],
        population_size=cfg['population_size'],
        elitism=cfg['elitism'],
        d2o_variation_rate=cfg['d2o_variation_rate']
    )

    tier_size = cfg['population_size'] // 3

    # ========== GENERATION 0 ==========
    logger.info("\n>>> GENERATION 0 - Creating initial population")

    # population_ordered is the population in its original order.
    # This order is used to generate filenames: population_ordered[i] -> chr{i+1}.
    # It must be kept unchanged (no in-place sorting) so that rename_tier1_files
    # can correctly look up file indices in subsequent generations.
    population_ordered = generator.generate_initial_population()
    logger.info(f"Initial population: {len(population_ordered)} unique chromosomes")

    # Generate PDBs: population_ordered[0] -> chr001, [1] -> chr002, ...
    generate_deuterated_pdbs(str(pdb_path), population_ordered, output_dir, generation=0)

    # Run SANS simulation
    primus_dir = run_batch_processing(output_dir, cfg['batch_script'])

    # Evaluate fitness (dat files alphabetical = chr001..chrN = population_ordered order)
    evaluate_fitness(
        primus_dir,
        population_ordered,
        q_max=cfg['q_max'],
        ratio_threshold=cfg['ratio_threshold'],
        deut_ref=cfg['deut_ref'],
        prot_ref=cfg['prot_ref']
    )

    # Sort for display and selection (highest fitness first)
    sorted_pop = sorted(population_ordered, key=lambda x: x.fitness if x.fitness else 0, reverse=True)
    display_population_summary(sorted_pop, generation=0)
    save_population_summary(sorted_pop, output_dir, generation=0)

    # Record best chromosome of generation 0
    save_best_fitness_summary(sorted_pop[0], generation=0, summary_path=best_summary_path)

    # ========== SUBSEQUENT GENERATIONS ==========
    for gen in range(1, cfg['generations']):
        logger.info("\n" + "=" * 80)
        logger.info(f">>> GENERATION {gen} - Population evolution")
        logger.info("=" * 80)

        # Generate next generation from sorted_pop (highest fitness first).
        # generate_next_generation returns tier1 + tier2 + tier3 in that order.
        new_population_ordered = generator.generate_next_generation(
            previous_population=sorted_pop,
            mutation_rate=cfg['mutation_rate'],
            crossover_rate=cfg['crossover_rate'],
            d2o_variation_rate=cfg['d2o_variation_rate']
        )
        logger.info(f"New population: {len(new_population_ordered)} chromosomes")

        # Tier1 chromosomes are always the first tier_size entries.
        # They are the selected individuals carried over from the previous generation.
        tier1 = new_population_ordered[:tier_size]
        tier2_and_tier3 = new_population_ordered[tier_size:]

        # Rename tier1 PDB and SANS files from gen(N-1) to gen(N).
        # CRITICAL: pass population_ordered (the previous generation's ORDERED population,
        # matching filename indices), NOT sorted_pop (sorted order would give wrong indices).
        rename_tier1_files(
            tier1=tier1,
            prev_population_ordered=population_ordered,
            output_dir=output_dir,
            primus_dir=primus_dir,
            prev_gen=gen - 1,
            new_gen=gen
        )

        # Remove remaining (non-tier1) files from the previous generation
        cleanup_non_tier1_files(
            output_dir=output_dir,
            primus_dir=primus_dir,
            generation=gen - 1
        )

        # Generate PDB files for tier2 and tier3 chromosomes only.
        # They start at index tier_size+1 so their filenames do not conflict with the
        # already-renamed tier1 files (chr001 .. chr{tier_size}).
        generate_deuterated_pdbs(
            str(pdb_path),
            tier2_and_tier3,
            output_dir,
            generation=gen,
            start_index=tier_size + 1
        )

        # Run SANS
        primus_dir = run_batch_processing(output_dir, cfg['batch_script'])

        # Evaluate fitness.
        # new_population_ordered[i] was written as chr{i+1}, so the alphabetical order
        # of dat files matches the population order.
        evaluate_fitness(
            primus_dir,
            new_population_ordered,
            q_max=cfg['q_max'],
            ratio_threshold=cfg['ratio_threshold'],
            deut_ref=cfg['deut_ref'],
            prot_ref=cfg['prot_ref']
        )

        # Sort for display and next-generation selection (highest fitness first)
        sorted_pop = sorted(
            new_population_ordered,
            key=lambda x: x.fitness if x.fitness else 0,
            reverse=True
        )
        display_population_summary(sorted_pop, generation=gen)
        save_population_summary(sorted_pop, output_dir, generation=gen)

        # Record best chromosome of this generation
        save_best_fitness_summary(sorted_pop[0], generation=gen, summary_path=best_summary_path)

        # Update population_ordered for the next iteration:
        # new_population_ordered is now the ordered population whose filenames will be
        # looked up in the next call to rename_tier1_files.
        population_ordered = new_population_ordered

    # ========== FINAL SUMMARY ==========
    logger.info("\n" + "=" * 80)
    logger.info("GENETIC ALGORITHM COMPLETED SUCCESSFULLY!")
    logger.info("=" * 80)
    logger.info(f"Total generations    : {cfg['generations']}")
    logger.info(f"Total PDBs generated : {cfg['generations'] * cfg['population_size']}")
    logger.info(f"Results in           : {output_dir.absolute()}")
    logger.info(f"SANS data in         : {primus_dir}")
    logger.info(f"Best fitness summary : {best_summary_path.absolute()}")

    if sorted_pop:
        best = sorted_pop[0]
        logger.info(f"\n>>> Best solution found:")
        logger.info(f"  D2O: {best.d2o}%")
        logger.info(f"  Deuterated amino acids: {sum(best.deuteration)}/20")
        logger.info(f"  Fitness: {best.fitness:.6f}")
        logger.info(f"  PDB: {generate_pdb_filename(best, 1, cfg['generations'] - 1)}")

    logger.info("=" * 80)


if __name__ == "__main__":
    try:
        start = time.perf_counter()
        main()
        end = time.perf_counter()
        print(f"Execution time: {end - start:.6f} seconds")
    except KeyboardInterrupt:
        logger.warning("\nInterrupted by user")
        sys.exit(1)
    except Exception as e:
        logger.exception(f"Fatal error: {e}")
        sys.exit(1)
